Club house project
Leon-Mbegera/members-only pull request #1
Opened 2021-06-18 15:48 UTC by Leon-Mbegera

2021-06-18 17:13 UTC, SajjadAhmad14 commented on app/views/devise/passwords/edit.html.erb
> +    <% end %>
Please create a helper under app/helpers and move this logic there. [OPTIONAL]

2021-06-18 17:18 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] README has all the instructions to run the project locally.
- [x] Commit messages are descriptive.
## To Improve 🙏
- [ ] Please use proper Git flow. The main/master branch should be there which is used for production releases.
- [ ] PR should have a descriptive summary.
- [ ] User should be able to sign in. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_requirement.png).
- [ ] A signed-in user you can create a new post. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png)
- [ ] A signed-in user can see the post's author. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png).
- [ ] User should be able to sign out. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png).
- [ ] A guest user can only see the post's text. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png).
- [ ] Sign in/Sign out links should be present in any view of the app. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png).
- [ ] Posts controller should use #before_action to :new and :create. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png).
- [ ] Project does not have Users controller. Please make sure it has a controller in order to authenticate the user.
- [ ] App has no functionality as per requirements. The app shows only this page:
![issues](https://user-images.githubusercontent.com/35504149/122596244-ffbf8700-d082-11eb-9a23-242ec5834b68.png)

- [ ] Please see inline comments for reference.
# Optional
- [ ] Views should be completely separate from app logic. You can use app/helpers to move all of your view-related logic.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-19 12:16 UTC, Leon-Mbegera commented
I have addressed all the requested changes herein,
Thanks for the straightforward guidelines on what to change.
gracias`

2021-06-19 13:04 UTC, george-shammar requested changes
### **STATUS:CHANGES REQUIRED** :recycle: :recycle: :construction: :construction_worker_man: 

Decent effort on this project. :+1: 

**Highlight**

- [x] Thank you for using the correct gitflow and implementing some of the required changes.

Please see required changes below:

- [x] As a signed-in user, you can create a new post. There is no where on your page to create a new post without manually editing the url which is not ideal.
- [x] A signed-in user should be able to see the post's author. But if posts cannot be created, it can't be seen.
- [x] A guest user should only see the post's text. Same reason as above - post cannot be created.
- [x] Sign in/Sign out links should be present in any view of the app. There is no way to link other pages of the application. 
- [ ] Project does not have Users controller. In trying to implement this, you have created a huge "User" directory and commented out every code inside all the files. Please get rid of all commented unused codes.

Please make the required changes and submit another CRR when you're ready.

In need of clarification or support, please drop your message here and ping me on slack.

Cheers and happy coding. :+1: :smile:

2021-06-19 14:22 UTC, Leon-Mbegera commented
Herein, I have addressed the requested changes:

1. As a signed user, he/she can create a post
2. Only a signed-in user can see the author of a post
3. A guest user can only see the post text
4. I've displayed sign up/sign in, and sign out links on every page. Possible to navigate to other pages
5. I've deleted all unused code in the user controller.

2021-06-19 14:45 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL
- [ ] You can show flash messages for success and failure for user-friendliness.
- [ ] Views should be completely separate from app logic. Please move view-related logic under app/helpers.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-19 19:24 UTC, merged